/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example */

#ifndef _Included_example
#define _Included_example
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
