/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static int bluescape_getInfo(int getInfo) {
    return exampleJNI.bluescape_getInfo(getInfo);
  }

  public static int bluescape_connect(int connect) {
    return exampleJNI.bluescape_connect(connect);
  }

  public static int bluescape_status(int status) {
    return exampleJNI.bluescape_status(status);
  }

  public static int bluescape_close(int close) {
    return exampleJNI.bluescape_close(close);
  }

  public static int bluescape_moveRight(int moveRight) {
    return exampleJNI.bluescape_moveRight(moveRight);
  }

  public static int bluescape_moveLeft(int moveLeft) {
    return exampleJNI.bluescape_moveLeft(moveLeft);
  }

}
