/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class exampleJNI {
  public final static native int bluescape_getInfo(int jarg1);
  public final static native int bluescape_connect(int jarg1);
  public final static native int bluescape_status(int jarg1);
  public final static native int bluescape_close(int jarg1);
  public final static native int bluescape_moveLeft(int jarg1);
  public final static native int bluescape_moveRight(int jarg1);
}